apiVersion: apps/v1
kind: Deployment
metadata:
  name: dao-governance-celery
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: celery
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: dao_governance.settings.production 