apiVersion: apps/v1
kind: Deployment
metadata:
  name: dao-governance-web
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: web
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: dao_governance.settings.production
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30 