apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dao-governance-mongo
spec:
  template:
    spec:
      containers:
      - name: mongo
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      resources:
        requests:
          storage: 50Gi 