apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dao-governance-neo4j
spec:
  template:
    spec:
      containers:
      - name: neo4j
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
          limits:
            cpu: 2000m
            memory: 8Gi
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      resources:
        requests:
          storage: 50Gi 