apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dao-governance-vault
spec:
  replicas: 3
  template:
    metadata:
      labels:
        topology.kubernetes.io/region: ${REGION}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dao-governance
              - key: component
                operator: In
                values:
                - vault
            topologyKey: "topology.kubernetes.io/zone"
      containers:
      - name: vault
        env:
        - name: VAULT_RAFT_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VAULT_REGION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['topology.kubernetes.io/region']
        - name: VAULT_API_ADDR
          value: "https://$(VAULT_REGION).vault.dao-governance.example.com"
        - name: VAULT_CLUSTER_ADDR
          value: "https://$(VAULT_RAFT_NODE_ID).dao-governance-vault-internal.dao-governance-multi-region.svc.cluster.local:8201"
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        volumeMounts:
        - name: vault-data
          mountPath: /vault/data
        - name: vault-config
          mountPath: /vault/config
        - name: vault-tls
          mountPath: /vault/tls
      volumes:
      - name: vault-config
        configMap:
          name: vault-config-multi-region
      - name: vault-tls
        secret:
          secretName: vault-tls 