apiVersion: apps/v1
kind: Deployment
metadata:
  name: dao-governance-web
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dao-governance
              - key: component
                operator: In
                values:
                - web
            topologyKey: "topology.kubernetes.io/zone"
      containers:
      - name: web
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: dao_governance.settings.multi_region
        - name: REGION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['topology.kubernetes.io/region']
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi 