apiVersion: v1
kind: ResourceQuota
metadata:
  name: dao-governance-quota
  labels:
    app: dao-governance
spec:
  hard:
    # Compute resources
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Storage resources
    requests.storage: 100Gi
    persistentvolumeclaims: 20
    
    # Object count limits
    pods: 50
    services: 20
    configmaps: 30
    secrets: 30
    
    # Load balancer limits
    services.loadbalancers: 1 