apiVersion: apps/v1
kind: Deployment
metadata:
  name: dao-governance-celery
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: celery
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: dao_governance.settings.staging 