apiVersion: apps/v1
kind: Deployment
metadata:
  name: dao-governance-web
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: web
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: dao_governance.settings.staging 